spring:
  thymeleaf:
    mode: HTML5
  application:
    name: server
  session:
    store-type: redis
server:
  port: 80
  servlet:
    session:
      cookie:
        name: mangooa-server
mangooa:
  server:
    init:
      enable: true
      domain: .mangooa.com
      admin:
        email: weimin.gao@aliyun.com
